services:
  server:
    build:
      target: deps
    command: sh -c "pnpm --filter @hiworld/server codegen && pnpm --filter @hiworld/server dev"
    environment:
      NODE_ENV: development
    volumes:
      - ./apps/server:/repo/apps/server
      - server-root-node-modules:/repo/node_modules
      - server-app-node-modules:/repo/apps/server/node_modules

  client:
    build:
      target: deps
    command: pnpm --filter @hiworld/client dev
    environment:
      HOST: 0.0.0.0
      WDS_SOCKET_PORT: ${CLIENT_PORT:-3000}
      REACT_APP_GRAPHQL_ENDPOINT: ${REACT_APP_GRAPHQL_ENDPOINT:-http://localhost:5000/}
    ports: !override
      - "${CLIENT_PORT:-3000}:3000"
    volumes:
      - ./apps/client:/repo/apps/client
      - client-root-node-modules:/repo/node_modules
      - client-app-node-modules:/repo/apps/client/node_modules

volumes:
  server-root-node-modules:
  server-app-node-modules:
  client-root-node-modules:
  client-app-node-modules:
